[package]
name = "rsa_ringsign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
rsa = "0.5.0"
rand = "0.8.4"
hex = "0.4.0"
sha2 ="0.9.8"

